/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.apache.maven.plugins:maven-compiler-plugin:3.10.1")
    implementation("org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7")
    implementation("org.seleniumhq.selenium:selenium-java:4.2.1")
    implementation("io.appium:java-client:8.1.1")
    implementation("io.cucumber:cucumber-java:7.7.0")
    implementation("commons-io:commons-io:2.6")
    implementation("io.cucumber:cucumber-core:7.7.0")
    implementation("io.cucumber:gherkin:24.0.0")
    implementation("tech.grasshopper:extentreports-cucumber7-adapter:1.7.0")
    testImplementation("io.cucumber:cucumber-junit:7.7.0")
    testImplementation("io.cucumber:cucumber-picocontainer:7.7.0")
}

group = "Payback"
version = "0.0.1-SNAPSHOT"
description = "Mobile"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
